# API KEYS DE TWIITER
API_KEY = 'INGRESAR_LA_API_KEY'
API_SECRET_KEY = 'INGRESAR_LA_API_SECRET_KEY'
ACCESS_TOKEN = 'INGRESAR_EL_ACCESS_TOKEN'
ACCESS_TOKEN_SECRET = 'INGRESAR_EL_ACCESS_TOKEN_SECRET'

# KAFKA
SERVER_KAFKA = 'localhost:9092'
TOPIC_NAME = 'twitter' # NOMBRE DEL TOPIC DE KAFKA

# CONFIGURACION PARA BUSQUEDA DE TUITS
TRACKS = ['#argentina','argentina','boca','river','ronaldo','messi','psg','barcelona','manchesterd']
LOCATION = [-126.2,-56.0,22.3,58.9]
LANGUAGES = ['en','es']