version: '3.8'
services:

  zoo-1:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zoo-1
    hostname: zoo-1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./volume/zookeeper/data:/data
      - ./volume/zookeeper/datalog:/datalog
    networks:
     - kakfa-net

  kafka-1:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volume/kafka/data:/var/lib/kafka/data
    depends_on:
      - zoo-1
    networks:
     - kakfa-net

networks:
  kakfa-net: